name: ny_articles
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  retrofit: ^4.0.3
  collection: ^1.17.2
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_inappwebview: ^5.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.2
  mockito: ^5.4.2
  bloc_test: ^9.1.5
  test_cov_console: ^0.2.2



flutter:
  uses-material-design: true


  assets:
    - .env
    - assets/images/
    - assets/test_response/
