// Mocks generated by Mockito 5.4.2 from annotations
// in ny_articles/test/features/articles/domain/usecases/get_articles_list_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ny_articles/core/data/remote/response_state.dart' as _i2;
import 'package:ny_articles/features/articles/data/models/articles_response.dart'
    as _i5;
import 'package:ny_articles/features/articles/domain/repositories/articles_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseState_0<T> extends _i1.SmartFake
    implements _i2.ResponseState<T> {
  _FakeResponseState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArticlesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesRepository extends _i1.Mock
    implements _i3.ArticlesRepository {
  @override
  _i4.Future<_i2.ResponseState<_i5.ArticleResponse?>> getArticlesList(
          String? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticlesList,
          [period],
        ),
        returnValue: _i4.Future<_i2.ResponseState<_i5.ArticleResponse?>>.value(
            _FakeResponseState_0<_i5.ArticleResponse?>(
          this,
          Invocation.method(
            #getArticlesList,
            [period],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ResponseState<_i5.ArticleResponse?>>.value(
                _FakeResponseState_0<_i5.ArticleResponse?>(
          this,
          Invocation.method(
            #getArticlesList,
            [period],
          ),
        )),
      ) as _i4.Future<_i2.ResponseState<_i5.ArticleResponse?>>);
}
